"""Genre taxonomy and subject mapping for Nuvio-style tile generation."""

GENRES = [
    {"slug": "action", "title": "ACTION", "subject": "action"},
    {"slug": "adventure", "title": "ADVENTURE", "subject": "adventure"},
    {"slug": "animation", "title": "ANIMATION", "subject": "animation"},
    {"slug": "anime", "title": "ANIME", "subject": "anime"},
    {"slug": "biography", "title": "BIOGRAPHY", "subject": "biography"},
    {"slug": "classic", "title": "CLASSIC", "subject": "classic"},
    {"slug": "comedy", "title": "COMEDY", "subject": "comedy"},
    {"slug": "crime", "title": "CRIME", "subject": "crime"},
    {"slug": "cult", "title": "CULT", "subject": "cult"},
    {"slug": "disaster", "title": "DISASTER", "subject": "disaster"},
    {"slug": "documentary", "title": "DOCUMENTARY", "subject": "documentary"},
    {"slug": "drama", "title": "DRAMA", "subject": "drama"},
    {"slug": "epic", "title": "EPIC", "subject": "epic"},
    {"slug": "faith", "title": "FAITH", "subject": "faith"},
    {"slug": "family", "title": "FAMILY", "subject": "family"},
    {"slug": "fantasy", "title": "FANTASY", "subject": "fantasy"},
    {"slug": "food", "title": "FOOD", "subject": "chef"},
    {"slug": "game-shows", "title": "GAME SHOWS", "subject": "game-shows"},
    {"slug": "heist", "title": "HEIST", "subject": "heist"},
    {"slug": "history", "title": "HISTORY", "subject": "history"},
    {"slug": "holiday", "title": "HOLIDAY", "subject": "holiday"},
    {"slug": "horror", "title": "HORROR", "subject": "horror"},
    {"slug": "indie", "title": "INDIE", "subject": "indie"},
    {"slug": "kids", "title": "KIDS", "subject": "kids"},
    {"slug": "k-drama", "title": "K-DRAMA", "subject": "k-drama"},
    {"slug": "j-drama", "title": "J-DRAMA", "subject": "j-drama"},
    {"slug": "c-drama", "title": "C-DRAMA", "subject": "c-drama"},
    {"slug": "legal", "title": "LEGAL", "subject": "legal"},
    {"slug": "mafia", "title": "MAFIA", "subject": "mafia"},
    {"slug": "martial-arts", "title": "MARTIAL ARTS", "subject": "martial-arts"},
    {"slug": "medical", "title": "MEDICAL", "subject": "medical"},
    {"slug": "music", "title": "MUSIC", "subject": "music"},
    {"slug": "musicals", "title": "MUSICALS", "subject": "musicals"},
    {"slug": "mystery", "title": "MYSTERY", "subject": "mystery"},
    {"slug": "nature", "title": "NATURE", "subject": "nature"},
    {"slug": "noir", "title": "NOIR", "subject": "noir"},
    {"slug": "paranormal", "title": "PARANORMAL", "subject": "paranormal"},
    {"slug": "period-drama", "title": "PERIOD DRAMA", "subject": "period-drama"},
    {"slug": "political", "title": "POLITICAL", "subject": "political"},
    {"slug": "psychological", "title": "PSYCHOLOGICAL", "subject": "psychological"},
    {"slug": "reality", "title": "REALITY", "subject": "reality"},
    {"slug": "road-trip", "title": "ROAD TRIP", "subject": "road-trip"},
    {"slug": "romance", "title": "ROMANCE", "subject": "romance"},
    {"slug": "satire", "title": "SATIRE", "subject": "satire"},
    {"slug": "sci-fi", "title": "SCI-FI", "subject": "sci-fi"},
    {"slug": "short-films", "title": "SHORT FILMS", "subject": "short-films"},
    {"slug": "soap", "title": "SOAP", "subject": "soap"},
    {"slug": "space", "title": "SPACE", "subject": "space"},
    {"slug": "sports", "title": "SPORTS", "subject": "sports"},
    {"slug": "stand-up", "title": "STAND-UP", "subject": "stand-up"},
    {"slug": "superhero", "title": "SUPERHERO", "subject": "superhero"},
    {"slug": "survival", "title": "SURVIVAL", "subject": "survival"},
    {"slug": "teen", "title": "TEEN", "subject": "teen"},
    {"slug": "thriller", "title": "THRILLER", "subject": "thriller"},
    {"slug": "travel", "title": "TRAVEL", "subject": "travel"},
    {"slug": "true-crime", "title": "TRUE CRIME", "subject": "true-crime"},
    {"slug": "urban", "title": "URBAN", "subject": "urban"},
    {"slug": "war", "title": "WAR", "subject": "war"},
    {"slug": "western", "title": "WESTERN", "subject": "western"},
    {"slug": "wrestling", "title": "WRESTLING", "subject": "wrestling"},
    {"slug": "zombies", "title": "ZOMBIES", "subject": "zombies"},
]

VARIANTS = ("normal", "focused", "dark")
